export const sampleCourses = [
  {
    id: 1,
    universityName: "Harvard University",
    programName: "Master of Business Administration",
    worldRanking: 3,
    studyLevel: "Master's Degree",
    location: { city: "Cambridge", country: "United States" },
    nextIntake: "September 2025",
    entryScore: "IELTS 7.5",
    annualTuition: { amount: 73440, currency: "USD" },
    category: "Business",
  },
  {
    id: 2,
    universityName: "Stanford University",
    programName: "PhD in Computer Science",
    worldRanking: 2,
    studyLevel: "PhD",
    location: { city: "Stanford", country: "United States" },
    nextIntake: "January 2026",
    entryScore: "IELTS 7.0",
    annualTuition: { amount: 58416, currency: "USD" },
    category: "Technology",
  },
  {
    id: 3,
    universityName: "University of Oxford",
    programName: "Master of Engineering Science",
    worldRanking: 1,
    studyLevel: "Master's Degree",
    location: { city: "Oxford", country: "United Kingdom" },
    nextIntake: "October 2025",
    entryScore: "IELTS 7.5",
    annualTuition: { amount: 32760, currency: "GBP" },
    category: "Engineering",
  },
  {
    id: 4,
    universityName: "MIT",
    programName: "Master of Science in Artificial Intelligence",
    worldRanking: 5,
    studyLevel: "Master's Degree",
    location: { city: "Cambridge", country: "United States" },
    nextIntake: "September 2025",
    entryScore: "IELTS 7.0",
    annualTuition: { amount: 59750, currency: "USD" },
    category: "Technology",
  },
  {
    id: 5,
    universityName: "University of Cambridge",
    programName: "PhD in Medicine",
    worldRanking: 4,
    studyLevel: "PhD",
    location: { city: "Cambridge", country: "United Kingdom" },
    nextIntake: "October 2025",
    entryScore: "IELTS 8.0",
    annualTuition: { amount: 35000, currency: "GBP" },
    category: "Medicine",
  },
  {
    id: 6,
    universityName: "University of Toronto",
    programName: "Master of Public Health",
    worldRanking: 25,
    studyLevel: "Master's Degree",
    location: { city: "Toronto", country: "Canada" },
    nextIntake: "September 2025",
    entryScore: "IELTS 6.5",
    annualTuition: { amount: 28000, currency: "CAD" },
    category: "Health",
  },
  {
    id: 7,
    universityName: "ETH Zurich",
    programName: "Master in Data Science",
    worldRanking: 11,
    studyLevel: "Master's Degree",
    location: { city: "Zurich", country: "Switzerland" },
    nextIntake: "September 2025",
    entryScore: "IELTS 7.0",
    annualTuition: { amount: 1500, currency: "CHF" },
    category: "Technology",
  },
  {
    id: 8,
    universityName: "University of Melbourne",
    programName: "Master of Architecture",
    worldRanking: 33,
    studyLevel: "Master's Degree",
    location: { city: "Melbourne", country: "Australia" },
    nextIntake: "February 2026",
    entryScore: "IELTS 6.5",
    annualTuition: { amount: 45000, currency: "AUD" },
    category: "Architecture",
  },
  {
    id: 9,
    universityName: "National University of Singapore",
    programName: "Master of Finance",
    worldRanking: 19,
    studyLevel: "Master's Degree",
    location: { city: "Singapore", country: "Singapore" },
    nextIntake: "August 2025",
    entryScore: "IELTS 7.0",
    annualTuition: { amount: 58000, currency: "SGD" },
    category: "Business",
  },
  {
    id: 10,
    universityName: "University of Edinburgh",
    programName: "PhD in Psychology",
    worldRanking: 30,
    studyLevel: "PhD",
    location: { city: "Edinburgh", country: "United Kingdom" },
    nextIntake: "September 2025",
    entryScore: "IELTS 7.5",
    annualTuition: { amount: 27500, currency: "GBP" },
    category: "Psychology",
  },
];

export const sortOptions = [
  { value: "popularity", label: "Popularity" },
  { value: "ranking", label: "University Ranking" },
  { value: "tuition-low", label: "Tuition (Low to High)" },
  { value: "tuition-high", label: "Tuition (High to Low)" },
  { value: "alphabetical", label: "A-Z" },
];

export const studyDestinations = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Sweden",
  "Switzerland",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "United Arab Emirates",
  "Other",
];
export const studyLevels = [
  "Foundation",
  "Diploma",
  "Bachelor's Degree",
  "Master's Degree",
  "PhD/Doctorate",
  "Postgraduate Diploma",
  "Professional Certificate",
  "Other",
];
export const lastCertificates = [
  "High School Diploma",
  "A-Levels",
  "IB Diploma",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Professional Certificate",
  "Other",
];
